- hosts: localhost
  gather_facts: False
  tasks:
    - name: import variables
      include_vars: vars/vpc_setup

    - name: VPC setup
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCIDR}}"
        region: "{{region}}"
        state : "{{state}}"
        dns_support: yes
        dns_hostnames: yes
      register: vpcout

    - debug:
        var: vpcout


    - name: Create subnet
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{Pubsub1CIDR}}"
        state: "{{state}}"
        region: "{{region}}"
        az: "{{zone1}}"
        map_public: yes
        tags:
          Name: subnet1
      register: subout1

    - name: Create subnet
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{Pubsub2CIDR}}"
        state: "{{state}}"
        region: "{{region}}"
        az: "{{zone2}}"
        map_public: yes
        tags:
          Name: subnet2
      register: subout2

    - name: Create subnet
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{Pubsub3CIDR}}"
        state: "{{state}}"
        region: "{{region}}"
        az: "{{zone3}}"
        map_public: yes
        tags:
          Name: subnet3
      register: subout3

    - name: Create subnet
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{Prisub1CIDR}}"
        state: "{{state}}"
        region: "{{region}}"
        az: "{{zone1}}"
        tags:
          Name: subnet1-priv
      register: subout1priv

    - name: Create subnet
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{Prisub2CIDR}}"
        state: "{{state}}"
        region: "{{region}}"
        az: "{{zone2}}"
        tags:
          Name: subnet2-priv
      register: subout2priv

    - name: Create subnet
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        cidr: "{{Prisub3CIDR}}"
        state: "{{state}}"
        region: "{{region}}"
        az: "{{zone3}}"
        tags:
          Name: subnet3-priv
      register: subout3priv

    - name: create Internet gateway
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        state: "{{state}}"
        region: "{{region}}"
        tags:
          Name: IGW1
          register: IGWpub


















